"""
Read/write helper for `controller-policy.local.toml` — the machine-generated
overrides file the config GUI owns (deep-merged over the documented defaults by
controller-router._load_policy). No tomlkit on SteamOS, so this emits a minimal
but valid TOML for the limited shapes the GUI produces: a flat top-level table
(`[quit_combo]`) plus dotted sub-tables (`[systems.nes]`, `[backends.cemu]`,
`[quit_combo.switch]`). Values may be bool / int / float / str / list-of-those.
"""
from __future__ import annotations

import os
import tomllib
from pathlib import Path

from . import staterev


def load(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        with path.open("rb") as f:
            return tomllib.load(f)
    except (tomllib.TOMLDecodeError, OSError):
        return {}


def _esc(s: str) -> str:
    """Escape a string for a TOML basic (double-quoted) value/key — backslash,
    quote, AND the control chars that would otherwise emit TOML tomllib rejects
    (a newline in a user-created collection name silently wiped ALL overrides)."""
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t"))


def _val(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + _esc(v) + '"'
    if isinstance(v, list):
        return "[" + ", ".join(_val(x) for x in v) + "]"
    raise TypeError(f"unsupported TOML value: {v!r}")


def _key(k: str) -> str:
    """A TOML table-key segment: bare if it's only [A-Za-z0-9_-], else quoted —
    so a collection display name like `Pew-Pew-Pew!!!` becomes a valid
    `[collections."Pew-Pew-Pew!!!"]` header."""
    import re
    if re.fullmatch(r"[A-Za-z0-9_-]+", k):
        return k
    return '"' + _esc(k) + '"'


def _table(name: str, tbl: dict) -> list[str]:
    """Emit `[name]` with its scalar/list keys; recurse into dict children as
    dotted sub-tables (`[name.child]`). `name` is already the full dotted path."""
    scalars = {k: v for k, v in tbl.items() if not isinstance(v, dict)}
    out = [f"[{name}]"]
    # _key() on the SCALAR keys too — a key like a cemu templates vid:pid
    # ("054c:0ce6") emitted bare is invalid TOML, and load() silently returns {}
    # on a decode error → ALL overrides would be wiped on the next save.
    out += [f"{_key(k)} = {_val(v)}" for k, v in scalars.items()]
    out.append("")
    for k, v in tbl.items():
        if isinstance(v, dict):
            out += _table(f"{name}.{_key(k)}", v)
    return out


def dump(path: Path, data: dict) -> None:
    """Write `data` (e.g. {'systems': {'nes': {...}}, 'quit_combo': {...}})."""
    lines = ["# Auto-generated by router-config-gui — overrides the documented",
             "# controller-policy.toml defaults. Safe to delete to reset.", ""]
    # top-level scalar tables first (quit_combo), then nested namespaces
    for name, tbl in data.items():
        if isinstance(tbl, dict):
            scal = {k: v for k, v in tbl.items() if not isinstance(v, dict)}
            kids = {k: v for k, v in tbl.items() if isinstance(v, dict)}
            if scal:
                lines.append(f"[{name}]")
                lines += [f"{_key(k)} = {_val(v)}" for k, v in scal.items()]
                lines.append("")
            for ck, cv in kids.items():
                lines += _table(f"{name}.{_key(ck)}", cv)
    text = "\n".join(lines) + "\n"
    # Atomic write — never leave a truncated/corrupt override file if interrupted.
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
        staterev.bump("config")     # invalidate cached page data (Preview, …)
    except OSError:
        try:
            tmp.unlink()
        except OSError:
            pass
        raise
